name: test

on: [push, pull_request]

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 73, 74 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer install
        run: composer install
      - name: PHP Unit tests for PHP ${{ matrix.php }}
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      - name: Send code coverage
        run: |
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer install
        run: composer install
      - name: Run codestyle check
        run: vendor/bin/phpcs